bucket_name = "dashboard_in"
gsheet_name = "Service Incident Tracker"
tab_name = "MASTER"
GOOGLE_APPLICATION_CREDENTIALS = "gcp_account_json_key.json"
# GOOGLE_APPLICATION_CREDENTIALS = "C:/Users/x244425/Documents/dashboard-293900-1.json"