# g-chat room aiops_zabbix
webhook_url_zbx: "https://chat.googleapis.com/v1/spaces/AAAAuwtQdFk/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=ANa88kSkOk-6mebYdu1nOZyoGJDIVpTyX90-zjlLi-o%3D"

# g-chat room aiops_chatbot
webhook_url_bot: "https://chat.googleapis.com/v1/spaces/AAAASbYD9iM/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=px1Il0OBcHtRTVUDHzH13xdi3R8itggmvpYk8a8oIRA%3D"

# slack TELUS-NaaS2 aiops_slack1
webhook_url_slack1: "https://hooks.slack.com/services/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"

# slack TELUS-NaaS2 aiops_slack1
webhook_url_slack2: https://hooks.slack.com/services/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

# slack TELUS-NaaS2 aiops_slack1
webhook_url_snow1: https://dev99406.service-now.com/api/576929/webhookdemo

# gsheet name for edge info 
gsheet_name: "zbxhost_nsg_list"

# nms name for locating edge info from g-sheet
nms_name: "naas_vsd"




 